Added shouldNotBeInRange for ClosedRange #119
javatarz/Kluent pull request #1
Opened 2019-10-20 07:20 UTC by Kshitij09

Signed-off-by: Kshitij09 <kshitijpatil98@gmail.com>

# Description
Added `shouldNotBeInRange` as per the discussion in #160

# Checklist

- [ ] I've added my name to the `AUTHORS` file, if it wasn't already present.

2019-10-23 14:14 UTC, Kshitij09 commented
Let me know if I should Add name in the `AUTHORS` file.

2019-10-27 10:23 UTC, javatarz commented
You should add your name @Kshitij09. Also, can you resolve conflicts please?

2019-10-27 10:23 UTC, javatarz commented
Also, there aren't any tests for the method you just added :(

2019-10-27 15:40 UTC, Kshitij09 commented
Okay. I'll do that soon

2019-10-30 15:25 UTC, Kshitij09 commented
I'm a bit confused about the caller and parameter for `shouldBeInRange` assertion.

Referring to issue #119  from the parent repo, it's mentioned as:

```
val r1 = 1..9
val r2 = 4..5

r1 shouldBeInRange r2 //fail
r2 shouldBeInRange r1 //pass
```

whereas, in your part of implementation, it works for exact opposite

```
val targetRange: IntRange = 1..9
val inputRange = 4..5

targetRange.shouldBeInRange(inputRange)  // pass
inputRange.shouldBeInRange(targetRange) // fail
```

So I'm not sure what should be in whose range? please clarify the same.

2019-10-30 18:43 UTC, Kshitij09 commented
# Checklist

- [x] I've added my name to the AUTHORS file, if it wasn't already present.

2020-01-15 07:08 UTC, javatarz requested changes

2020-01-15 07:08 UTC, javatarz commented on AUTHORS.md
> +1. Kshitij Patil [@Kshitij09](https://github.com/Kshitij09) ([Contributions](https://github.com/MarkusAmshove/Kluent/commits?author=ChristianIvicevic))
You probably want to link to https://github.com/MarkusAmshove/Kluent/commits?author=Kshitij09 :)

2020-01-15 07:10 UTC, javatarz approved these changes

2020-01-15 07:10 UTC, merged